
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhinav Ranjan
 */
public class AddQuestions extends javax.swing.JFrame {

    /**
     * Creates new form AddQuestions
     */
    public AddQuestions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Submit2 = new javax.swing.JButton();
        Submit1 = new javax.swing.JButton();
        Submit3 = new javax.swing.JButton();
        Semester = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Questions = new javax.swing.JTextArea();
        Difficulty = new javax.swing.JComboBox<>();
        Module = new javax.swing.JComboBox<>();
        Subject = new javax.swing.JComboBox<>();
        Branch = new javax.swing.JComboBox<>();
        QuestionID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel5.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel2.setText("Add Questions");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(320, 40, 360, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Branch:-");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(420, 430, 120, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Difficulty of Question:-");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(310, 270, 160, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Question ID:-");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(370, 130, 120, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Module:-");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(410, 300, 120, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Your Question:-");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(360, 200, 120, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Semester:-");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(400, 340, 120, 17);

        Submit.setBackground(new java.awt.Color(51, 255, 255));
        Submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel5.add(Submit);
        Submit.setBounds(360, 470, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Subject:-");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(410, 380, 120, 17);

        Submit2.setBackground(new java.awt.Color(51, 255, 255));
        Submit2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit2.setText("View Questions");
        Submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit2ActionPerformed(evt);
            }
        });
        jPanel5.add(Submit2);
        Submit2.setBounds(760, 110, 200, 50);

        Submit1.setBackground(new java.awt.Color(51, 255, 255));
        Submit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit1.setText("Reset");
        Submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit1ActionPerformed(evt);
            }
        });
        jPanel5.add(Submit1);
        Submit1.setBounds(520, 470, 110, 30);

        Submit3.setBackground(new java.awt.Color(51, 255, 255));
        Submit3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit3.setText("Generate Tab");
        Submit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit3ActionPerformed(evt);
            }
        });
        jPanel5.add(Submit3);
        Submit3.setBounds(760, 30, 200, 50);

        Semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel5.add(Semester);
        Semester.setBounds(490, 340, 130, 20);

        Questions.setColumns(20);
        Questions.setRows(5);
        jScrollPane1.setViewportView(Questions);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(490, 180, 250, 70);

        Difficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));
        Difficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DifficultyActionPerformed(evt);
            }
        });
        jPanel5.add(Difficulty);
        Difficulty.setBounds(490, 270, 130, 20);

        Module.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Module 1", "Module 2", "Module 4" }));
        jPanel5.add(Module);
        Module.setBounds(490, 310, 130, 20);

        Subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maths", "DATA STRUCTURE", "SOFT SKILLS", "OPERATING SYSYTEM", "PYTHON", "JAVA", "C++", "C", "BEEE", "PHYSICS", "BIOLOGY", "CHEMISTRY", "ED" }));
        jPanel5.add(Subject);
        Subject.setBounds(490, 380, 140, 20);

        Branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BE-CSE", "BE-IT", "BE-CIVIL", "BE-MECHANICAL", "BE-CHEMICAL", "BE-PETROLEUM", "BA-LLB", "BBA-LLB", "MBA", "BJMC", "BSc ANIMATION", "BBA", "BCA", "MCA", "MTECH" }));
        Branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchActionPerformed(evt);
            }
        });
        jPanel5.add(Branch);
        Branch.setBounds(490, 430, 140, 20);
        jPanel5.add(QuestionID);
        QuestionID.setBounds(490, 130, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abhinav Ranjan\\Desktop\\Desktop\\rayas-azules-en-el-fondo-blanco-81719187-002.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 520);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 969, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        Connection conn= null;
        PreparedStatement pt= null;
        ResultSet rst=null;
        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            conn=DriverManager.getConnection("jdbc:ucanaccess://D:\\ppppp\\Questions.accdb");

            pt = conn.prepareStatement("Insert into Questions(QuestionID,YourQuestion,DifficultyOfQuestion,Module,Semester,Subject,Branch)values(?,?,?,?,?,?,?)");
            pt.setString(1,QuestionID.getText());
            pt.setString(2,Questions.getText());
            pt.setString(3,(String) Difficulty.getSelectedItem());
            pt.setString(4,(String) Module.getSelectedItem());
            pt.setString(5,(String) Semester.getSelectedItem());
            pt.setString(6,(String) Subject.getSelectedItem());
            pt.setString(7,(String)Branch.getSelectedItem());
            pt.execute();

            JOptionPane.showMessageDialog(null,"Submitted");
        }

        catch (HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);}
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void Submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit1ActionPerformed

        Questions.setText(null);
        Difficulty.setSelectedItem(null);
        Module.setSelectedItem(null);
        Semester.setSelectedItem(null);
        Subject.setSelectedItem(null);
        Branch.setSelectedItem(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_Submit1ActionPerformed

    private void DifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DifficultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DifficultyActionPerformed

    private void BranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BranchActionPerformed

    private void Submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit2ActionPerformed
ShowQuestions obj = new ShowQuestions ();   
 obj.show();        // TODO add your handling code here:
    }//GEN-LAST:event_Submit2ActionPerformed

    private void Submit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit3ActionPerformed
        // TODO add your handling code here:
        CreateQuestionPaper obj = new CreateQuestionPaper ();
        obj.show();
    }//GEN-LAST:event_Submit3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Branch;
    private javax.swing.JComboBox<String> Difficulty;
    private javax.swing.JComboBox<String> Module;
    private javax.swing.JTextField QuestionID;
    private javax.swing.JTextArea Questions;
    private javax.swing.JComboBox<String> Semester;
    private javax.swing.JComboBox<String> Subject;
    private javax.swing.JButton Submit;
    private javax.swing.JButton Submit1;
    private javax.swing.JButton Submit2;
    private javax.swing.JButton Submit3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
