
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.security.auth.Subject;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhinav Ranjan
 */
public class ShowQuestions extends javax.swing.JFrame {

    /**
     * Creates new form ShowQuestions
     */
    public ShowQuestions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Show = new javax.swing.JButton();
        Branch = new javax.swing.JComboBox<>();
        Semester = new javax.swing.JComboBox<>();
        Subject = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Show1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        QTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel11 = new javax.swing.JLabel();

        jPanel6.setLayout(null);

        Show.setBackground(new java.awt.Color(51, 255, 255));
        Show.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Show.setText("Show");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        jPanel6.add(Show);
        Show.setBounds(130, 300, 80, 30);

        Branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BE-CSE", "BE-IT", "BE-CIVIL", "BE-MECHANICAL", "BE-CHEMICAL", "BE-PETROLEUM", "BA-LLB", "BBA-LLB", "MBA", "BJMC", "BSc ANIMATION", "BBA", "BCA", "MCA", "MTECH" }));
        Branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchActionPerformed(evt);
            }
        });
        jPanel6.add(Branch);
        Branch.setBounds(270, 110, 100, 20);

        Semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        Semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemesterActionPerformed(evt);
            }
        });
        jPanel6.add(Semester);
        Semester.setBounds(270, 170, 100, 20);

        Subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maths", "DATA STRUCTURE", "SOFT SKILLS", "OPERATING SYSYTEM", "PYTHON", "JAVA", "C++", "C", "BEEE", "PHYSICS", "BIOLOGY", "CHEMISTRY", "ED",}));
        Subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectActionPerformed(evt);
            }
        });
        jPanel6.add(Subject);
        Subject.setBounds(270, 220, 100, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Semester:-");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(120, 160, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Paper Of Branch:-");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(120, 100, 130, 40);

        jLabel12.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel12.setText("View Questions");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(30, 20, 360, 40);

        Show1.setBackground(new java.awt.Color(51, 255, 255));
        Show1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Show1.setText("Reset");
        Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show1ActionPerformed(evt);
            }
        });
        jPanel6.add(Show1);
        Show1.setBounds(250, 300, 80, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Subject:-");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(120, 220, 80, 30);

        QTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "QUESTION", "DIFFICULTY", "MODULE", "SEMESTER", "SUBJECT", "BRANCH"
            }
        ));
        jScrollPane3.setViewportView(QTable);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(390, 40, 570, 110);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abhinav Ranjan\\Desktop\\Desktop\\rayas-azules-en-el-fondo-blanco-81719187-002.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(0, 0, 970, 520);
        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(200, 40, 2, 2);

        jLabel11.setText("jLabel11");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(620, 100, 40, 14);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 969, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        Connection conn= null;
        PreparedStatement pst= null;
        ResultSet rs=null;
        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            conn=DriverManager.getConnection("jdbc:ucanaccess://D:\\ppppp\\Questions.accdb");
            String sql ="select * from Questions where Branch = '"+Branch.getSelectedItem()+"'and Semester='" +Semester.getSelectedItem()+"'and Subject ='" +Subject.getSelectedItem()+"'";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            QTable.setModel(DbUtils.resultSetToTableModel(rs));

            {

                JOptionPane.showMessageDialog(null,"Here's the Question:");

            }
        }
        catch (HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);}

        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowActionPerformed

    private void BranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BranchActionPerformed

    private void SemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemesterActionPerformed

    private void SubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectActionPerformed

    private void Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show1ActionPerformed
        // TODO add your handling code here:

        Semester.setSelectedItem(null);
        Subject.setSelectedItem(null);
        Branch.setSelectedItem(null);

    }//GEN-LAST:event_Show1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Branch;
    private javax.swing.JTable QTable;
    private javax.swing.JComboBox<String> Semester;
    private javax.swing.JButton Show;
    private javax.swing.JButton Show1;
    private javax.swing.JComboBox<String> Subject;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
